name: Simple CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Use the Node.js version appropriate for your project

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm test

      - name: Build
        run: npm run build
